In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_excel('crop_csv_file.xlsx')

In [3]:
data

,State_Name,District_Name,Crop_Year,Season,Crop,Temperature,humidity,soil moisture,area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,36,35,45,1254.0,2000.00
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,37,40,46,2.0,1.00
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,36,41,50,102.0,321.00
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,37,42,55,176.0,641.00
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,36,40,54,720.0,165.00
5,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Coconut,34,45,52,18168.0,65100000.00
6,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Dry ginger,34,55,62,36.0,100.00
7,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Sugarcane,35,50,59,1.0,2.00
8,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Sweet potato,25,55,55,5.0,15.00
9,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Tapioca,36,35,45,40.0,169.00
10,Andaman and Nicobar Islands,NICOBARS,2001,Kharif,Arecanut,37,40,46,1254.0,2061.00
11,Andaman and Nicobar Islands,NICOBARS,2001,Kharif,Other Kharif pulses,36,41,50,2.0,1.00
12,Andaman and Nicobar Islands,NICOBARS,2001,Kharif,Rice,37,42,55,83.0,300.00
13,Andaman and Nicobar Islands,NICOBARS,2001,Whole Year,Cashewnut,36,40,54,719.0,192.00
14,Andaman and Nicobar Islands,NICOBARS,2001,Whole Year,Coconut,34,45,52,18190.0,64430000.00
15,Andaman and Nicobar Islands,NICOBARS,2001,Whole Year,Dry ginger,34,55,62,46.0,100.00
16,Andaman and Nicobar Islands,NICOBARS,2001,Whole Year,Sugarcane,35,50,59,1.0,1.00
17,Andaman and Nicobar Islands,NICOBARS,2001,Whole Year,Sweet potato,25,55,55,11.0,33.00
18,Andaman and Nicobar Islands,NICOBARS,2002,Kharif,Rice,36,35,45,189.2,510.84
19,Andaman and Nicobar Islands,NICOBARS,2002,Whole Year,Arecanut,37,40,46,1258.0,2083.00
20,Andaman and Nicobar Islands,NICOBARS,2002,Whole Year,Banana,36,41,50,213.0,1278.00
21,Andaman and Nicobar Islands,NICOBARS,2002,Whole Year,Black pepper,37,42,55,63.0,13.50
22,Andaman and Nicobar Islands,NICOBARS,2002,Whole Year,Cashewnut,36,40,54,719.0,208.00
23,Andaman and Nicobar Islands,NICOBARS,2002,Whole Year,Coconut,34,45,52,18240.0,67490000.00
24,Andaman and Nicobar Islands,NICOBARS,2002,Whole Year,Dry chillies,34,55,62,413.0,28.80
25,Andaman and Nicobar Islands,NICOBARS,2002,Whole Year,Dry ginger,35,50,59,47.3,133.00
26,Andaman and Nicobar Islands,NICOBARS,2002,Whole Year,Sugarcane,25,55,55,5.0,40.00
27,Andaman and Nicobar Islands,NICOBARS,2003,Kharif,Rice,36,35,45,52.0,90.17
28,Andaman and Nicobar Islands,NICOBARS,2003,Whole Year,Arecanut,37,40,46,1261.0,1525.00
29,Andaman and Nicobar Islands,NICOBARS,2003,Whole Year,Banana,36,41,50,266.0,1763.00
...,...,...,...,...,...,...,...,...,...,...
49969,Chhattisgarh,JANJGIR-CHAMPA,2005,Rabi,Rapeseed &Mustard,36,41,50,2550.0,765.00
49970,Chhattisgarh,JANJGIR-CHAMPA,2005,Rabi,Safflower,37,42,55,34.0,8.00
49971,Chhattisgarh,JANJGIR-CHAMPA,2005,Rabi,Urad,36,40,54,102.0,29.00
49972,Chhattisgarh,JANJGIR-CHAMPA,2005,Rabi,Wheat,34,45,52,2918.0,3010.00
49973,Chhattisgarh,JANJGIR-CHAMPA,2005,Whole Year,Banana,34,55,62,10.0,341.00
49974,Chhattisgarh,JANJGIR-CHAMPA,2005,Whole Year,Coriander,35,50,59,58.0,15.00
49975,Chhattisgarh,JANJGIR-CHAMPA,2005,Whole Year,Dry chillies,25,55,55,546.0,127.00
49976,Chhattisgarh,JANJGIR-CHAMPA,2005,Whole Year,Dry ginger,36,35,45,7.0,7.00
49977,Chhattisgarh,JANJGIR-CHAMPA,2005,Whole Year,Garlic,37,40,46,16.0,54.00
49978,Chhattisgarh,JANJGIR-CHAMPA,2005,Whole Year,Onion,36,41,50,369.0,2353.00
49979,Chhattisgarh,JANJGIR-CHAMPA,2005,Whole Year,Potato,37,42,55,267.0,1223.00
49980,Chhattisgarh,JANJGIR-CHAMPA,2005,Whole Year,Sannhamp,36,40,54,72.0,27.00
49981,Chhattisgarh,JANJGIR-CHAMPA,2005,Whole Year,Sugarcane,34,45,52,66.0,203.00
49982,Chhattisgarh,JANJGIR-CHAMPA,2005,Whole Year,Sweet potato,34,55,62,28.0,182.00
49983,Chhattisgarh,JANJGIR-CHAMPA,2005,Whole Year,Turmeric,35,50,59,7.0,6.00
49984,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Arhar/Tur,25,55,55,1256.0,580.00
49985,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Castor seed,36,35,45,17.0,5.00
49986,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Groundnut,37,40,46,1118.0,1408.00
49987,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Horse-gram,36,41,50,171.0,51.00
49988,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Maize,37,42,55,431.0,567.00
49989,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Mesta,36,40,54,28.0,60.00
49990,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Moong(Green Gram),34,45,52,244.0,53.00
49991,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Other Kharif pulses,34,55,62,233.0,110.00
49992,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Rice,35,50,59,278916.0,528694.00
49993,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Sesamum,25,55,55,829.0,247.00
49994,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Small millets,36,35,45,27.0,7.00
49995,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Soyabean,37,40,46,27.0,32.00
49996,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Sunflower,36,41,50,450.0,213.00
49997,Chhattisgarh,JANJGIR-CHAMPA,2006,Kharif,Urad,37,42,55,1778.0,309.00
49998,Chhattisgarh,JANJGIR-CHAMPA,2006,Rabi,Gram,36,40,54,216.0,194.00

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Data columns (total 10 columns):
State_Name       49999 non-null object
District_Name    49999 non-null object
Crop_Year        49999 non-null int64
Season           49999 non-null object
Crop             49999 non-null object
Temperature      49999 non-null int64
humidity         49999 non-null int64
soil moisture    49999 non-null int64
 area            49999 non-null float64
Production       49784 non-null float64
dtypes: float64(2), int64(4), object(4)
memory usage: 3.8+ MB

In [5]:
#handling missing data
data = data.dropna()

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49784 entries, 0 to 49998
Data columns (total 10 columns):
State_Name       49784 non-null object
District_Name    49784 non-null object
Crop_Year        49784 non-null int64
Season           49784 non-null object
Crop             49784 non-null object
Temperature      49784 non-null int64
humidity         49784 non-null int64
soil moisture    49784 non-null int64
 area            49784 non-null float64
Production       49784 non-null float64
dtypes: float64(2), int64(4), object(4)
memory usage: 4.2+ MB

In [7]:
data.describe()

,Crop_Year,Temperature,humidity,soil moisture,area,Production
count,49784.000000,49784.000000,49784.000000,49784.000000,49784.000000,4.978400e+04
mean,2005.872087,34.445746,44.775269,53.109312,7393.028993,4.132019e+05
std,5.108602,3.498277,6.662586,5.259326,27983.253218,1.232609e+07
min,1997.000000,25.000000,35.000000,45.000000,0.200000,0.000000e+00
25%,2002.000000,34.000000,40.000000,50.000000,78.000000,8.700000e+01
50%,2006.000000,36.000000,42.000000,54.000000,441.000000,6.384400e+02
75%,2010.000000,36.000000,50.000000,55.000000,2567.000000,5.615000e+03
max,2014.000000,37.000000,55.000000,62.000000,877029.000000,7.801620e+08

In [8]:
le = LabelEncoder()

crop = le.fit_transform(data.Crop)
Season = le.fit_transform(data.Season)

NameError: name 'LabelEncoder' is not defined